### ISSUE TITLE
User defined "top species" list.

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/irecord-app#150] opened 2018-03-19 14:54 UTC
If I look at my "statistics" I see a list of the species I have most often recorded sorted in numerical order.  This list appears to basis for the species list presented when I go to create a new record.

I would really like the option to have a user defined species list offered here rather than one based on a list of species previously recorded.  This would also be very useful if recording species for specific activities, you could define an activity specific list.  Having a user defined list would certainly make my recording in the field quicker.

The current list contains 10 species.  Can we find space for a 10 item user defined list please.

Thanks.

**Comment by kazlauskis** [comment] 2018-03-19 18:56
Thanks, this is indeed a nice idea and I would like to see this too. A duplicate of #72

**Closed by kazlauskis** 2018-03-19 18:56 UTC
Labels: duplicate
