### ISSUE TITLE
Auto-order recorded species lists alphabetically

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/irecord-app#151] opened 2018-03-21 14:00 UTC
Could the species on a plant list be automatically ordered alphabetically to make it easier to scroll down a list to see what has already been recorded? Ordering preferably by scientific name, although this could perhaps be an option.

**Comment by kazlauskis** [comment] 2018-03-21 19:52
Is this is what recorders would do, look at the past species alphabetically instead of the order of entry?

**Comment by kazlauskis** [comment] 2018-03-21 20:10
Duplicate of #140

**Closed by kazlauskis** 2018-03-21 20:10 UTC
Labels: duplicate

**Comment by sacrevert** [comment] 2018-03-21 20:44
Sorry for duplicating, I didn't notice the duplicates, and didn't see that anyone had replied to me when I had asked previously about adding them.

**Comment by kazlauskis** [comment] 2018-03-21 20:50
Hey, no worries, I should tidy up the issues backlog to make things more visible really.
